{% set name = "biosphere" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d92a5736130491a24169c2e987ec207524a3c579a6fce47d8845bf14c41e12ab

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - maturin                                # [build_platform != target_platform]
  host:
    - python
    - pip
    - maturin
  run:
    - python
    - numpy

test:
  imports:
    - biosphere
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/mlondschien/biosphere
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Simple, fast random forests
  description: |
    Random forests with a runtime of `O(n d log(n) + n_trees d n max_depth)` instead of `O(n_tree mtry n log(n) max_depth)`.
  dev_url: https://github.com/mlondschien/biosphere

extra:
  recipe-maintainers:
    - mlondschien
