{% set name = "biosphere" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 07ad2affea67cfdd2380263a74ad4ffbe9ad1e2c4436ad4411ab2987cd125631

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - pip
    - maturin
  run:
    - python
    - numpy

test:
  imports:
    - biosphere
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/mlondschien/biosphere
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Simple, fast random forests
  description: |
    Random forests with a runtime of `O(n d log(n) + n_trees d n max_depth)` instead of `O(n_tree mtry n log(n) max_depth)`.
  dev_url: https://github.com/mlondschien/biosphere

extra:
  recipe-maintainers:
    - mlondschien
